Insert into dbo.AlunosPorSalas Values (1999, 35.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2000, 33.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2001, 26.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2002, 26.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2003, 26.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2004, 26.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2005, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2006, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (1999, 22.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2000, 22.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2001, 20.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2002, 20.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2003, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2004, 20, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2005, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (2006, 20.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.AlunosPorSalas Values (1999, 36.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2000, 36.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2001, 26, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2002, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2003, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2004, 26.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2005, 25.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2006, 25.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (1999, 23.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2000, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2001, 23.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2002, 23.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2003, 24.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2004, 24.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2005, 24.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (2006, 25, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.AlunosPorSalas Values (1999, 39.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2000, 39.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2001, 30.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2002, 30.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2003, 29.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2004, 29.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2005, 29.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2006, 28.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (1999, 23.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2000, 23.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2001, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2002, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2003, 22.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2004, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2005, 23.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (2006, 24.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.AlunosPorSalas Values (1999, 29.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2000, 28, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2001, 22.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2002, 22.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2003, 21.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2004, 20.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2005, 20.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2006, 21.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (1999, 23.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2000, 24.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2001, 25.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2002, 23.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2003, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2004, 27.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2005, 27.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (2006, 26.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.AlunosPorSalas Values (1999, 40.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2000, 40.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2001, 30.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2002, 30.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2003, 29.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2004, 29.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2005, 29, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2006, 28.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (1999, 24.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2000, 24.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2001, 24.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2002, 23.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2003, 24.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2004, 24.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2005, 24.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (2006, 24.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.AlunosPorSalas Values (1999, 29.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2000, 29.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2001, 26.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2002, 26.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2003, 25.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2004, 25, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2005, 25.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2006, 25, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (1999, 25.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2000, 26.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2001, 25, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2002, 24.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2003, 23.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2004, 24.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2005, 24.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (2006, 24.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.AlunosPorSalas Values (1999, 34.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2000, 32.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2001, 26.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2002, 25.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2003, 25.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2004, 24.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2005, 23.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2006, 23.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (1999, 19.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2000, 20.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2001, 26.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2002, 20.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2003, 19.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2004, 20, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2005, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (2006, 19.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.AlunosPorSalas Values (1999, 36.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2000, 36.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2001, 28.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2002, 28, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2003, 27.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2004, 27.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2005, 19.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2006, 26.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (1999, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2000, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2001, 22.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2002, 22.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2003, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2004, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2005, 23.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (2006, 22.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.AlunosPorSalas Values (1999, 34.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2000, 33.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2001, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2002, 25.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2003, 24.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2004, 24.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2005, 23.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2006, 22.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (1999, 20.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2000, 20, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2001, 20.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2002, 20, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2003, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2004, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2005, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (2006, 20.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.AlunosPorSalas Values (1999, 31.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2000, 31.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2001, 27.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2002, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2003, 26.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2004, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2005, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2006, 25.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (1999, 22, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2000, 21.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2001, 21.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2002, 20.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2003, 21.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2004, 21.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2005, 21.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (2006, 20.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.AlunosPorSalas Values (1999, 30.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2000, 30.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2001, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2002, 26.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2003, 26.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2004, 26.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2005, 26.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2006, 25.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (1999, 22.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2000, 21.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2001, 21.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2002, 20.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2003, 20.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2004, 20.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2005, 20.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (2006, 20.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.AlunosPorSalas Values (1999, 22.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2000, 35.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2001, 28.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2002, 28.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2003, 28, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2004, 27.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2005, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2006, 25.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (1999, 21.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2000, 21, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2001, 19.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2002, 19.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2003, 19.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2004, 19, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2005, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (2006, 19.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.AlunosPorSalas Values (1999, 40.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2000, 39.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2001, 32.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2002, 32.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2003, 31.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2004, 30.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2005, 29.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2006, 29.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (1999, 22.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2000, 21.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2001, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2002, 19.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2003, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2004, 19.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2005, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (2006, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.AlunosPorSalas Values (1999, 39.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2000, 38.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2001, 33.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2002, 33.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2003, 33.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2004, 33.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2005, 32.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2006, 32.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (1999, 25.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2000, 24.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2001, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2002, 22.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2003, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2004, 23.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2005, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (2006, 23.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.AlunosPorSalas Values (1999, 35, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2000, 34.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2001, 29.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2002, 29, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2003, 28.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2004, 28.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2005, 27, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2006, 27, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (1999, 22, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2000, 21.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2001, 21.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2002, 21.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2003, 21.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2004, 21.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2005, 22.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (2006, 22.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.AlunosPorSalas Values (1999, 37.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2000, 36.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2001, 28.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2002, 28.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2003, 28.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2004, 27.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2005, 27.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2006, 26.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (1999, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2000, 19.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2001, 19.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2002, 19.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2003, 19.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2004, 19.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2005, 20.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (2006, 19.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.AlunosPorSalas Values (1999, 33.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2000, 28.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2001, 28.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2002, 28.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2003, 28.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2004, 27.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2005, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2006, 26.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (1999, 24.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2000, 23.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2001, 23.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2002, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2003, 22.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2004, 22, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2005, 21.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (2006, 20.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.AlunosPorSalas Values (1999, 33.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2000, 32.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2001, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2002, 26.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2003, 26.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2004, 26.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2005, 25.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2006, 25.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (1999, 23.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2000, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2001, 22.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2002, 22.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2003, 22.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2004, 22.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2005, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (2006, 22.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.AlunosPorSalas Values (1999, 33.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2000, 32.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2001, 31.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2002, 22.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2003, 30.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2004, 30.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2005, 30.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2006, 29.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (1999, 22.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2000, 22.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2001, 21.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2002, 21.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2003, 21.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2004, 21.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2005, 21.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (2006, 21.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.AlunosPorSalas Values (1999, 36, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2000, 35.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2001, 33.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2002, 33.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2003, 32.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2004, 32.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2005, 32.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2006, 32.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (1999, 24.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2000, 23.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2001, 23, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2002, 22.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2003, 22, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2004, 21.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2005, 21.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (2006, 21.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.AlunosPorSalas Values (1999, 32.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2000, 31.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2001, 29.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2002, 29.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2003, 29.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2004, 28.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2005, 28.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2006, 27.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (1999, 23.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2000, 23.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2001, 22.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2002, 22.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2003, 21.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2004, 21.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2005, 21, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (2006, 21, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.AlunosPorSalas Values (1999, 29, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2000, 28.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2001, 25.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2002, 25.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2003, 25.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2004, 25.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2005, 25.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2006, 24.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (1999, 24.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2000, 24, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2001, 23.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2002, 23, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2003, 22.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2004, 22.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2005, 21.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (2006, 21.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.AlunosPorSalas Values (1999, 25, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2000, 25, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2001, 22.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2002, 22.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2003, 22.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2004, 22, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2005, 21.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2006, 21.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (1999, 25.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2000, 25.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2001, 24.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2002, 24.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2003, 22.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2004, 24.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2005, 24.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (2006, 24, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.AlunosPorSalas Values (1999, 31.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2000, 30.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2001, 27.6, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2002, 28, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2003, 27.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2004, 27.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2005, 26.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2006, 26.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (1999, 18, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2000, 17.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2001, 27.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2002, 17.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2003, 17.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2004, 17.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2005, 17.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (2006, 17.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.AlunosPorSalas Values (1999, 30.5, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2000, 17.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2001, 26.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2002, 26.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2003, 26.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2004, 26.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2005, 25.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2006, 25.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (1999, 19.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2000, 19.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2001, 19.4, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2002, 19.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2003, 19, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2004, 19, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2005, 25.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (2006, 20, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.AlunosPorSalas Values (1999, 33.9, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2000, 33.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2001, 30.1, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2002, 29.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2003, 29.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2004, 29.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2005, 28.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2006, 28.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (1999, 19, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2000, 18.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2001, 19.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2002, 19.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2003, 19.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2004, 21.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2005, 21.3, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (2006, 20.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.AlunosPorSalas Values (1999, 33, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2000, 33.8, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2001, 31.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2002, 31.2, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2003, 31.3, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2004, 31.7, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2005, 32.4, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2006, 32, 'Unidade', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (1999, 26.1, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2000, 24.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2001, 24.8, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2002, 24.6, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2003, 24.2, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2004, 23.9, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2005, 23.5, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.AlunosPorSalas Values (2006, 23.7, 'Unidade', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
