Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 84, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 85.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 84.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 86.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 610008, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 97.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 96, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 84, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 88.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 90.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 82.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 93.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 96.4	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 91, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 93.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 93.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 86.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 83.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 72.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 98.3	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 95.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 94, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 94.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 95, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 94.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 98.2	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 76.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 75.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 77.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 73.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 79.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 83.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 91.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97.1	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 85.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 86.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 88, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 88.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 89.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 89.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 93	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 66.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 72.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 74, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 66.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 65.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 59.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 69, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 66.4	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 100, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 100, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 40.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 100, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 100, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97.3	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 88.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 92.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 91.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 92.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 92.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.1	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 82.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 84.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 85.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 86.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 87.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 96.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 96.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 96.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 92.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 87.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 93.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.8	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 94.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 94.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 98.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 96.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 95.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 96	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 59.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 57.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 67.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 67.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 77.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 96.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 96.6	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 86, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 79.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 82.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 87.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 85.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 90, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 88.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 92.6	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 67.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 68.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 84.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 84.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.4	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 56.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 57.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 60, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 67.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 75.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 75.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 88.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 88.4	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 66.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 62.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 60.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 73.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 73.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 79.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 90.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 94.9	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 70.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 70.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 72.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 81.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 87.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 92.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 86.7	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 86.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 87.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 91.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 90.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 92.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 93.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 78.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 79.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 78.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 81.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 84.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 87, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 92	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 74.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 72.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 76.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 86.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 84.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 89.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 89.7	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 82.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 84.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 85.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 87.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 84.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 94.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.3	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 88.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 87.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 86.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 88.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 86.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 90.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 88	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 85.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 85.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 89.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 86.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 90.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 89.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 88.6	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 95.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 95.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 95.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 94.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 95.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97.6	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 92.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 92.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 91.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 88.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 93.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 98.2	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 85.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 79.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 80.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 81.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 84.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 88.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 88.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 89.7	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 78.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 79.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 70.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 76.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 75.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 81.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 87.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 89.2	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 89.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 88, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 86, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 92.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 98, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 98.3	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 73.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 70.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 76.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 83.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 88.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 92.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 91.7	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 64, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 68.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 68, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 66.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 69.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 69.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 80.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 71.5	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 72, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 73.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 76.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 81.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 82.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 91.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 85.7	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 90.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 91.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 93, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 94.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 94.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 92.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 93.9	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 91.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 91.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 92.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 92.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 93.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.4	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 78, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 74.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 74.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 75, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 71.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 71.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 79.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 88.8	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 91, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 87.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 74.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 87.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 91.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 94.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 94.5	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 96.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 96.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 96.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 97.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 97.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 97.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 99.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.9	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 94.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 92.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 95.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 93.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 96.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 97.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 99.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.7	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 95.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 95.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 95.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 97.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 97, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 99.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 100, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.2	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 93.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 93, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 94.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 94.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 94.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 97.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 99.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97.6	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 96.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 97.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 97.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 97.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 97.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 97.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 99.4, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 100	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 93, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 94.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 95.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 95.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 95.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 100	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 73.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 76.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 76.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 79.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 77.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 83.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 92.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.1	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 91.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 90.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 94.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 94.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 98.8	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 94.8, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 91.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 90.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 90.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 91.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 92.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 94.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.6	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 96.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 94.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 94.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 94.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 93.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 95.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 96.4	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 89.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 89.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 92, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 89.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 91.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 95, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 96.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 97.5	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 92, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 92.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 91.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 89.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 92.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 93.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 94.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 94.7	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 79.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 84.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 82.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 84.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 87.6, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 90.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 97.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 88.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 87.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 89.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 90.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 90.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 93.4, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 98.2, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.9	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 88.3, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 87.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 60, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 60.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 63.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 69.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 89.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 91.8	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 81.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 81.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 77.6, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 75.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 83.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 90.5, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 94.1	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 98.7, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 96.1, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 96, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 97.2, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 99.5, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 99.9, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 100, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 100	, 'Porcentagem', 'Medio','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 93, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 94.8, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 91.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 91.7, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 94.3, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 93.9, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 99.1, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 99.5	, 'Porcentagem', 'Medio','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
