Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 26, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 28.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 27.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 28.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 28.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 45.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 56.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 59.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 26, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 51.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 56.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 53.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 60.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 62, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 65.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 66.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rondonia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 22.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 21.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 21.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 21.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 19.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 22.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 29.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 43.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 57, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 54.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 69, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 66.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 63.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 69, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 72.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 77.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Acre')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 18.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 17.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 19.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 20, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 23.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 54.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 54.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 63.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 39.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 42.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 43, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 45.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 48, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 58.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 64, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 65.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amazonas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 11.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 42.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 13.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 15.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 48, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 21.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 23.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 26.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 54.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 34.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 38.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 54, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 64.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 68.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 65.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 75, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Roraima')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 16.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 17.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 18.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 20.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 22.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 27, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 34.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 44.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 46.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 48.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 51.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 53, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 55.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 63.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 69.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 71.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Para')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 14.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 16.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 15.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 15.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 15.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 17.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 20.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 32, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 55.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 46.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 48.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 46.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 44.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 47, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 54.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 54.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Amapa')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 14.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 17, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 18.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 21.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 29.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 39.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 61.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 63.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 46.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 44.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 44.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 48.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 53.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 59.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 70.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 73.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Tocantins')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 7.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 8.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 8.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 12, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 17.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 28.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 30.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 34.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 25.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 27, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 30.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 34, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 35.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 44.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 52.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 52.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Maranhao')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 10.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 11.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 12.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 16.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 35.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 32.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 41.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 53.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 35.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 39.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 42.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 45.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 52.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 32.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 67.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 74.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Piaui')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 22.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 28.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 39.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 48.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 54.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 57.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 67.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 72.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 36.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 40.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 44.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 53.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 59.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 63.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 69.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 69.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Ceara')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 27.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 29.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 32.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 36.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 48, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 51, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 63.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 69, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 52.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 54.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 54.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 57.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 61.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 64, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 69.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 73.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Norte')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 36.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 38, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 39, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 51.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 51.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 53.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 62.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 67.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 57.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 58.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 59.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 57, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 60.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 62.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 67.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 67.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Paraiba')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 51.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 50.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 50.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 52.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 57.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 59.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 61.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 63.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 55, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 55.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 57.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 57.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 60.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 61.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 65, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 65.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Pernambuco')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 22.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 23.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 24.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 27, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 31.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 35.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 38, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 44.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 50.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 52.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 49.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 56, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 56, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 59.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 61.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 65.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Alagoas')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 24.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 24.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 49.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 27.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 46.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 55.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 62.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 71.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 40.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 39.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 45.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 27.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 58.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 67.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 73.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 77.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sergipe')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 14.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 16.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 17.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 20, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 22.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 22.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 24.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 26.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 36.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 37.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 41.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 44.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 46.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 47.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 49.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 51.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Bahia')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 53.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 54.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 56.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 60.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 62.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 47.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 66.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 80.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 74.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 74.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 75.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 76.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 78.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 80.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 82.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Minas Gerais')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 42.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 43.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 45.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 48.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 51, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 53.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 58.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 70.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 62.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 63.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 65.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 68.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 72, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 76.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 76.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 91.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Espirito Santo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 58.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 58.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 60.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 61, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 63.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 94.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 71.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 74.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 61, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 61, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 63.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 63.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 67.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 69.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 71.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 81.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio de Janeiro')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 71.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 74.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 76.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 81.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 85, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 87.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 95.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 77.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 77.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 79.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 80.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 82.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 87, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 88, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 74.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Sao Paulo')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 64.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 66.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 68.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 71, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 74.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 77.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 82.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 89, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 75.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 76.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 79.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 81, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 82.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 85.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 86.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 88.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Parana')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 51.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 53.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 57.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 61.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 65.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 72.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 79.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 85.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 72.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 74.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 78.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 78.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 82.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 84.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 87.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 89.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Santa Catarina')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 62.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 61.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 61.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 63.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 67.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 70.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 73.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 75.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 77.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 75.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 78.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 78.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 79.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 82.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 82.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Rio Grande do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 72.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 72.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 77.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 80, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 85, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 88.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 90.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 68.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 68.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 71, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 73, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 74.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 79, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 82.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 86.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso do Sul')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 45.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 51.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 53.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 73, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 62.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 64.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 75.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 77.5, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 66.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 69.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 72, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 72.9, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 75.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 79, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 82.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 86, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Mato Grosso')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 31.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 31.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 33.6, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 48.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 48.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 52.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 72.1, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 76.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 48.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 49, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 47.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 48.4, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 51.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 59.7, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 74.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 74.5, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Goias')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 75, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 75.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 75.7, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 73.9, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 75.2, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 77.4, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 82.3, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 90.8, 'Porcentagem', 'Fundamental','Publico', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (1999, 63.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2000, 65.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2001, 64, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2002, 66.1, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2003, 65.8, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2004, 68.6, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2005, 75.3, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));
Insert into dbo.ProfComSuperiorNoAnoes Values (2006, 78.2, 'Porcentagem', 'Fundamental','Privado', (Select Id from Estadoes where Nome like('Distrito Federal')));